---
title: "AG Hackathon Notebook"
output: html_notebook
---

Get libraries
```{r}
library(readr)
library("dplyr")
library("tidyr")
library("ggplot2")
```


Import data
Get Books from 5 specific languages
- Germany, French, eng-us, eng-gb, eng
```{r}
books <- read_csv("/Users/thandekachehore/Documents/GitHub/allangrayhackathon/ML/books.csv")
booksActive = as_tibble(books) %>% filter(language_code %in% c("eng", "en-US", "en-GB", "en-CA"))
```

View data
```{r}
summary(booksActive) #quantitative summary of table
head(booksActive) #first 5 results
```

List top 10 books with more than 10 ratings

```{r}
top10BooksRatings = top_n(booksActive, 10, ratings_count) %>% 
  select(title, authors, average_rating, language_code, ratings_count)
```


-Get number of authors
-Count number of books by each of the top 20 authors

```{r}
authorCountPrelim = booksActive %>% group_by(authors) %>% tally() 
authorNum = length(unique(authorCountPrelim)$n)
authorCount = top_n(authorCountPrelim, 20, n)
```

Join data. Retain only rows in both sets.
```{r}
join2 = select(books2nd, book_isbn, book_format, book_rating, book_rating_count, book_review_count)
join2 <- join2 %>% rename(isbn13 = book_isbn) 



```




Clustering
```{r}
ClusDataset = sample_n(booksActive, 2500)
```


